version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=swi2chatapp'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
  rabbitmq:
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_PASSWORD: guest
      RABBITMQ_DEFAULT_USER: guest
    ports:
      - "5672:5672"
      - "15672:15672"