spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/swi2chatapp
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
  main:
    allow-bean-definition-overriding: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html
jwt:
  secret: 6D8586CDBDC816E3ED9541A1F17CE6D8586CDBDC816E3ED9541A1F17CE
  expiration:
    ms: 600000
  refresh-expiration:
    ms: 86400000
